name: Deploy preview site

on:
  push:
    branches:
      - preview

permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Build preview site
        run: bundle exec jekyll build --config _config.yml,_config.preview.yml

      - name: Add preview CNAME
        run: rm -f _site/CNAME

      - name: Deploy preview site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: _site
          clean: true
          target-folder: preview
